import Header from "@/components/Header";
import React from "react";
import "./globals.css";
export const metadata = {
  title: "Work Manager",
  description: "Generated by create next app",
};
const layout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Header childrens={children} />
      </body>
    </html>
  );
};

export default layout;
